### ISSUE TITLE
Crash when starting - java.lang.RuntimeException: Unable to start activity -- window decor. 

### ISSUE THREAD

**Issue by carstenhag** [lhoyong/ImagePickerView#1]
Hey, just tried it out inside https://github.com/weg-li/weg-li-android (you can see the code there, just include the imagepicker and you can see the crash).

Using version 1.4.5 of the library I'm getting this exception:

```
2020-05-22 20:49:48.358 8088-8088/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.weg_li_android, PID: 8088
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.weg_li_android/com.lhoyong.imagepicker.ui.Gallery}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:421)
        at androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:150)
        at com.lhoyong.imagepicker.ui.Gallery.configureToolbar(Gallery.kt:166)
```

**Comment by lhoyong** [comment]
Hi @carstenhag , this issue fixed versions `1.4.10` and i'm checked yr project head [commit](https://github.com/weg-li/weg-li-android/commit/ff36f7162d95ff410c3443a2ad6ac7aee7803670)

if y try again with `1.4.10` same or different problems occur, please send an issue or pr
